server:
  port: ${PORT:8081}
  servlet:
    context-path: /

# JPA - HIBERNATE
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true


  datasource:
    url: 
    username:
    password:
    hikari:
      maximum-pool-size: 10

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_SENDER_USERNAME}
    password: ${SPRING_MAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

### MULTIPART (MultipartProperties)
## Enable multipart uploads

#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 1KB
#      max-file-size: 100MB
  ## Threshold after which files are written to disk.
  ## Max file size.
  ## Max Request Size
  #spring.servlet.multipart.max-request-size=215MB
  #
  ### File Storage Properties
  ## All files uploaded through the REST API will be stored in this directory
  #file.upload-dir=./uploads
#  images.upload.folder=C://cooperativeFiles//images//