CREATE TABLE contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company TEXT,
    name TEXT,
    surname TEXT,
    country TEXT,
    website TEXT,
    skype TEXT,
    viber TEXT,
    whats_app TEXT,
    we_chat TEXT,
    linked_in TEXT,
    business_type TEXT,
    comments TEXT
);