CREATE TABLE email
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        INT                      NOT NULL,
    recipient      BIGINT                   NOT NULL,
    subject        TEXT,
    created_on     TIMESTAMP WITH TIME ZONE NOT NULL,
    content        TEXT
);