CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL,
    username varchar(250) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    email varchar(250) NOT NULL UNIQUE,
    enabled boolean NOT NULL DEFAULT TRUE,
    api_key varchar(250),
    api_secret varchar(250),
    client varchar(250),
    created_on timestamp NOT NULL,

    FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);